##########################
# å¤´åƒæ•ˆæœæ–‡å­—åŠé“¾æ¥è®¾ç½®
##########################
title: å´å€©è±ª
subtitle: ä¸ªäººç«™
description: å¤šåª’ä½“åˆ†æï¼Œè®¡ç®—æœºè§†è§‰
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: wqhIris
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: ä¸ç§¯è·¬æ­¥ï¼Œæ— ä»¥è‡³åƒé‡Œ
url: "http://wqhiris.github.io"
##########################


##########################ï¼Œ
# è¯„è®ºåŠŸèƒ½ï¼Œå€ŸåŠ©gitalkæ’ä»¶ï¼ˆhttps://github.com/gitalk/gitalkï¼‰
# å…·ä½“è®¾ç½®å‚è€ƒä»¥ä¸‹é“¾æ¥ï¼š
#    https://www.jianshu.com/p/656e6101bf0f
#    http://note.youdao.com/publicshare/?id=6ea132ba501b49b2928125a694cc9ad9#/
#    https://blog.csdn.net/weixin_34112208/article/details/87232126
##########################
comment:
    gitalk: true
    gitalk_clientID: '29ca6c79e20086448a19'
    gitalk_Secret: '56c1a901674f2ad625759ca4c869fd4dd773ea75'
    gitalk_repo: 'wqhIris.github.io'
    gitalk_owner: 'wqhIris'
    gitalk_admin: 'wqhIris'
    distractionFreeMode: true
##########################


##########################
# Social
# ç¤¾äº¤è”ç³»æ–¹å¼
##########################
social:
    weibo: 
    github: wqhIris 
    mail: wuqianhaoiris@gmail.com
    #mail2: wqhiris@163.com
##########################


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹

##########################
# é¢œè‰²è®¾ç½®
##########################
# å­—ä½“é¢œè‰²
textColor: #FF0000
# å°é¢èƒŒæ™¯å›¾ç‰‡é¢œè‰²
# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: purple #clear
##########################


##########################
# Navigation buttons in the front page.s
# å¯¼èˆªæ¡è®¾ç½®ï¼Œå¤´åƒç‚¹å‡»åŠ¨ä½œè·³è½¬è®¾ç½®ï¼ˆabout_buttonï¼‰
##########################
nav:
    - {title: è®ºæ–‡, description: è®ºæ–‡åŠä»£ç , url: '/archive'}   
    - {title: æ ‡ç­¾, description: åˆ†ç±», url: '/tags'}      
    - {title: åšå®¢ä¸»é¡µ, description: æˆ‘çš„åšå®¢, url: '/#blog'}   
# The about_button should not be removed.
about_button:
    title: å…³äºæˆ‘
    description: ä¸ªäººä¿¡æ¯åŠè”ç³»æ–¹å¼
##########################


##########################
# åšå®¢æ˜¾ç¤ºè®¾ç½®
##########################
# Pagination
# æ¯é¡µæ˜¾ç¤ºè®°å½•æ•°åŠæŒ‡ç¤ºæ–‡å­—
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"
# åšå®¢åå­—æ ¼å¼
permalink: /:year/:month/:title/
# Format 
# è®¾ç½®é«˜äº®
highlighter: rouge
##########################
